M48
; DRILL file KiCad 10.0.6 date 2026-09-06T12:07:46
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-06T12:07:46-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
%
G90
G05
T1
X182.245Y-103.325
T2
X155.575Y-73.66
X157.48Y-100.33
M30
